vti_encoding:SR|utf8-nl
vti_author:SR|DESKTOP-HJ9FAE6\\Cathy
vti_modifiedby:SR|LATITUDE-E5430\\gregaryb
vti_timelastmodified:TR|08 Mar 2024 11:11:13 -0000
vti_timecreated:TR|29 May 2023 07:26:58 -0000
vti_title:SR|Technology
vti_extenderversion:SR|12.0.0.0
vti_nexttolasttimemodified:TR|08 Mar 2024 11:10:58 -0000
vti_backlinkinfo:VX|NonFiction/Travel/Travel.php Specialist/FirstEditions/FirstEditions.php Children/Children.php Specialist/Shakespeare/Shakespeare.php NonFiction/Crafts/Crafts.php LearnToCode/LearnToCode.html Specialist/NationalGeographic/NationalGeographic.php Specialist/ReadersDigestCondensed/ReadersDigestCondensed.php NonFiction/Sports/Sports.php NonFiction/Reference/Reference.php Fiction/Action/Action.php Fiction/General/General.php NonFiction/Gardening/Gardening.php Fiction/ScienceFiction/default.html Requests/Requests.html index.php Specialist/AntiquePre1950/AntiquePre1950.php NonFiction/Outdoors/Outdoors.php NonFiction/Hobbies/Hobbies.php NonFiction/Humour/Humour.php Specialist/Classics/Classics.php Specialist/Miscellaneous/Miscellaneous.php Specialist/Series/Series.php master.dwt NonFiction/Religion/Religion.php Fiction/Action&Adventure/default.html Fiction/Political/default.html NonFiction/Biographies/default.html NonFiction/Cooking/Cooking.php NonFiction/AutoBiographies/AutoBiographies.php Specialist/Retro1975To2000/Retro1975To2000.php Specialist/MillsAndBoon/MillsAndBoon.php Emporium/Emporium.php FAQ/FAQ.php Fiction/Sagas/Sagas.php Facebook/Facebook.php Specialist/BoxSets/BoxSets.php YoungAdults/YoungAdults.html Fiction/Thrillers/Thrillers.php Fiction/Horror/Horror.php Fiction/Drama/default.html Fiction/Historical/default.html Fiction/Romance/Romance.php Fiction/Westerns/Westerners.html NonFiction/Technology/Technology.php NonFiction/World/World.php Specialist/Vintage1950To1975/Vintage1950To1975.php Specialist/Penguin/Penguin.php Fiction/Crime/Crime.php Fiction/Science/science.php Fiction/Fantasy/Fantasy.php NonFiction/Arts/Arts.php NonFiction/History/default.html ShoppingCart.html Fiction/Westerns/Westerns.php Fiction/Mystery/Mystery.php NonFiction/Education/Education.php NonFiction/Health/Health.php Specialist/ProlificAuthors/ProlificAuthors.php
vti_cacheddtm:TX|08 Mar 2024 11:11:12 -0000
vti_filesize:IR|14989
vti_cachedtitle:SR|Technology
vti_cachedbodystyle:SR|<body>
vti_cachedlinkinfo:VX|G|../../master.dwt Q|../../styles/style2.css S|../../global.js S|../../images/Logo.png S|../../images/Books.png H|../../index.htm H|../../FAQ/FAQ.php H|../../LearnToCode/LearnToCode.html H|../../Requests/Requests.html H|../../Children/Children.php H|../../Emporium/Emporium.php K|Technology.php H|../../Fiction/Action/Action.php H|../../Fiction/Crime/Crime.php H|../../Fiction/Fantasy.php H|../../Fiction/General/General.php H|../../Fiction/Horror/Horror.php H|../../Fiction/Mystery/Mystery.php H|../../Fiction/Romance/Romance.php H|../../Fiction/Sagas/Sagas.php H|../../Fiction/Science/science.php H|../../Fiction/Thrillers/Thrillers.php H|../../Fiction/Westerns/Westerners.html K|Technology.php H|../Arts/Arts.php H|../AutoBiographies/AutoBiographies.php H|../Cooking/Cooking.php H|../Crafts/Crafts.php H|../Education/Education.php H|../Gardening/Gardening.php H|../Health/Health.php H|../Hobbies/Hobbies.php H|../Humour/Humour.php H|../Outdoors/Outdoors.php H|../Reference/Reference.php H|../Religion/Religion.php H|../Sports/Sports.php H|Technology.php H|../Travel/Travel.php H|../World/World.php K|Technology.php H|../../Specialist/AntiquePre1950/AntiquePre1950.php H|../../Specialist/Vintage1950To1975/Vintage1950To1975.php H|../../Specialist/Retro1975To2000/Retro1975To2000.php H|../../Specialist/FirstEditions/FirstEditions.php H|../../Specialist/Classics/Classics.php H|../../Specialist/Shakespeare/Shakespeare.php H|../../Specialist/Penguin/Penguin.php H|../../Specialist/BoxSets/BoxSets.php H|../../Specialist/Series/Series.php H|../../Specialist/ProlificAuthors/ProlificAuthors.php H|../../Specialist/ReadersDigestCondensed/ReadersDigestCondensed.php H|../../Specialist/MillsAndBoon/MillsAndBoon.php H|../../Specialist/NationalGeographic/NationalGeographic.php H|../../Specialist/Miscellaneous/Miscellaneous.php H|../../Specialist/Penguin/Penguin.php S|../../images/top.png K|Technology.php S|../../images/home.png H|../../index.htm S|../../images/shopping_cart.png H|../../ShoppingCart.html S|../../images/shopping_cart.png
vti_cachedsvcrellinks:VX|FGUS|master.dwt FQUS|styles/style2.css FSUS|global.js FSUS|images/Logo.png FSUS|images/Books.png NHUS|index.htm FHUS|FAQ/FAQ.php FHUS|LearnToCode/LearnToCode.html FHUS|Requests/Requests.html FHUS|Children/Children.php FHUS|Emporium/Emporium.php FKUS|NonFiction/Technology/Technology.php FHUS|Fiction/Action/Action.php FHUS|Fiction/Crime/Crime.php NHUS|Fiction/Fantasy.php FHUS|Fiction/General/General.php FHUS|Fiction/Horror/Horror.php FHUS|Fiction/Mystery/Mystery.php FHUS|Fiction/Romance/Romance.php FHUS|Fiction/Sagas/Sagas.php FHUS|Fiction/Science/science.php FHUS|Fiction/Thrillers/Thrillers.php NHUS|Fiction/Westerns/Westerners.html FKUS|NonFiction/Technology/Technology.php FHUS|NonFiction/Arts/Arts.php FHUS|NonFiction/AutoBiographies/AutoBiographies.php FHUS|NonFiction/Cooking/Cooking.php FHUS|NonFiction/Crafts/Crafts.php FHUS|NonFiction/Education/Education.php FHUS|NonFiction/Gardening/Gardening.php FHUS|NonFiction/Health/Health.php FHUS|NonFiction/Hobbies/Hobbies.php FHUS|NonFiction/Humour/Humour.php FHUS|NonFiction/Outdoors/Outdoors.php FHUS|NonFiction/Reference/Reference.php FHUS|NonFiction/Religion/Religion.php FHUS|NonFiction/Sports/Sports.php FHUS|NonFiction/Technology/Technology.php FHUS|NonFiction/Travel/Travel.php FHUS|NonFiction/World/World.php FKUS|NonFiction/Technology/Technology.php FHUS|Specialist/AntiquePre1950/AntiquePre1950.php FHUS|Specialist/Vintage1950To1975/Vintage1950To1975.php FHUS|Specialist/Retro1975To2000/Retro1975To2000.php FHUS|Specialist/FirstEditions/FirstEditions.php FHUS|Specialist/Classics/Classics.php FHUS|Specialist/Shakespeare/Shakespeare.php FHUS|Specialist/Penguin/Penguin.php FHUS|Specialist/BoxSets/BoxSets.php FHUS|Specialist/Series/Series.php FHUS|Specialist/ProlificAuthors/ProlificAuthors.php FHUS|Specialist/ReadersDigestCondensed/ReadersDigestCondensed.php FHUS|Specialist/MillsAndBoon/MillsAndBoon.php FHUS|Specialist/NationalGeographic/NationalGeographic.php FHUS|Specialist/Miscellaneous/Miscellaneous.php FHUS|Specialist/Penguin/Penguin.php FSUS|images/top.png FKUS|NonFiction/Technology/Technology.php FSUS|images/home.png NHUS|index.htm FSUS|images/shopping_cart.png FHUS|ShoppingCart.html FSUS|images/shopping_cart.png
vti_cachedneedsrewrite:BR|false
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_metatags:VR|HTTP-EQUIV=Content-Type text/html;\\ charset=utf-8
vti_charset:SR|utf-8
