vti_encoding:SR|utf8-nl
vti_author:SR|DESKTOP-HJ9FAE6\\Cathy
vti_modifiedby:SR|LATITUDE-E5430\\gregaryb
vti_timelastmodified:TR|09 Mar 2024 12:56:02 -0000
vti_timecreated:TR|29 May 2023 07:26:58 -0000
vti_title:SR|Crime
vti_extenderversion:SR|12.0.0.0
vti_backlinkinfo:VX|NonFiction/Travel/Travel.php Specialist/FirstEditions/FirstEditions.php Children/Children.php Specialist/Shakespeare/Shakespeare.php ShoppingCart.php LearnToCode/LearnToCode.html NonFiction/Crafts/Crafts.php Specialist/NationalGeographic/NationalGeographic.php Specialist/ReadersDigestCondensed/ReadersDigestCondensed.php NonFiction/Reference/Reference.php NonFiction/Sports/Sports.php Specialist/ProlificAuthors/ProlificAuthors.php Fiction/Action/Action.php Fiction/Westerns/Westerns.php Fiction/Mystery/Mystery.php Fiction/General/General.php NonFiction/Education/Education.php NonFiction/Gardening/Gardening.php NonFiction/Health/Health.php Specialist/Series/Series.php NonFiction/Outdoors/Outdoors.php Specialist/AntiquePre1950/AntiquePre1950.php index.php NonFiction/Hobbies/Hobbies.php NonFiction/Humour/Humour.php Specialist/Classics/Classics.php Specialist/Miscellaneous/Miscellaneous.php master.dwt NonFiction/Religion/Religion.php Specialist/Retro1975To2000/Retro1975To2000.php NonFiction/AutoBiographies/AutoBiographies.php NonFiction/Cooking/Cooking.php Specialist/MillsAndBoon/MillsAndBoon.php Requests/Requests.php Facebook/Facebook.php FAQ/FAQ.php Emporium/Emporium.php Fiction/Sagas/Sagas.php Specialist/BoxSets/BoxSets.php Fiction/Horror/Horror.php Fiction/Thrillers/Thrillers.php YoungAdults/YoungAdults.php Fiction/Romance/Romance.php NonFiction/Technology/Technology.php NonFiction/World/World.php Specialist/Vintage1950To1975/Vintage1950To1975.php Fiction/Crime/Crime.php Specialist/Penguin/Penguin.php Fiction/Fantasy/Fantasy.php Fiction/Science/science.php NonFiction/Arts/Arts.php
vti_nexttolasttimemodified:TR|09 Mar 2024 12:55:25 -0000
vti_cacheddtm:TX|09 Mar 2024 12:56:02 -0000
vti_filesize:IR|12963
vti_cachedtitle:SR|Crime
vti_cachedbodystyle:SR|<body>
vti_cachedlinkinfo:VX|G|../../master.dwt Q|../../styles/style.css S|../../images/Logo.png S|../../images/Books.png H|../../index.htm H|../../FAQ/FAQ.php H|../../LearnToCode/LearnToCode.html H|../../Requests/Requests.php H|../../Children/Children.php H|../../Emporium/Emporium.php K|Crime.php H|../Action/Action.php H|Crime.php H|../Fantasy/Fantasy.php H|../General/General.php H|../Horror/Horror.php H|../Mystery/Mystery.php H|../Romance/Romance.php H|../Sagas/Sagas.php H|../Science/science.php H|../Thrillers/Thrillers.php H|../Westerns/Westerns.php K|Crime.php H|../../NonFiction/Arts/Arts.php H|../../NonFiction/AutoBiographies/AutoBiographies.php H|../../NonFiction/Cooking/Cooking.php H|../../NonFiction/Crafts/Crafts.php H|../../NonFiction/Education/Education.php H|../../NonFiction/Gardening/Gardening.php H|../../NonFiction/Health/Health.php H|../../NonFiction/Hobbies/Hobbies.php H|../../NonFiction/Humour/Humour.php H|../../NonFiction/Outdoors/Outdoors.php H|../../NonFiction/Reference/Reference.php H|../../NonFiction/Religion/Religion.php H|../../NonFiction/Sports/Sports.php H|../../NonFiction/Technology/Technology.php H|../../NonFiction/Travel/Travel.php H|../../NonFiction/World/World.php K|Crime.php H|../../Specialist/AntiquePre1950/AntiquePre1950.php H|../../Specialist/Vintage1950To1975/Vintage1950To1975.php H|../../Specialist/Retro1975To2000/Retro1975To2000.php H|../../Specialist/FirstEditions/FirstEditions.php H|../../Specialist/Classics/Classics.php H|../../Specialist/Shakespeare/Shakespeare.php H|../../Specialist/Penguin/Penguin.php H|../../Specialist/BoxSets/BoxSets.php H|../../Specialist/Series/Series.php H|../../Specialist/ProlificAuthors/ProlificAuthors.php H|../../Specialist/ReadersDigestCondensed/ReadersDigestCondensed.php H|../../Specialist/MillsAndBoon/MillsAndBoon.php H|../../Specialist/NationalGeographic/NationalGeographic.php H|../../Specialist/Miscellaneous/Miscellaneous.php H|../../Specialist/Penguin/Penguin.php H|../../YoungAdults/YoungAdults.php S|../../images/top.png K|Crime.php S|../../images/home.png H|../../index.htm S|../../images/shopping_cart.png H|../../ShoppingCart.php S|../../images/shopping_cart.png
vti_cachedsvcrellinks:VX|FGUS|master.dwt FQUS|styles/style.css FSUS|images/Logo.png FSUS|images/Books.png NHUS|index.htm FHUS|FAQ/FAQ.php FHUS|LearnToCode/LearnToCode.html FHUS|Requests/Requests.php FHUS|Children/Children.php FHUS|Emporium/Emporium.php FKUS|Fiction/Crime/Crime.php FHUS|Fiction/Action/Action.php FHUS|Fiction/Crime/Crime.php FHUS|Fiction/Fantasy/Fantasy.php FHUS|Fiction/General/General.php FHUS|Fiction/Horror/Horror.php FHUS|Fiction/Mystery/Mystery.php FHUS|Fiction/Romance/Romance.php FHUS|Fiction/Sagas/Sagas.php FHUS|Fiction/Science/science.php FHUS|Fiction/Thrillers/Thrillers.php FHUS|Fiction/Westerns/Westerns.php FKUS|Fiction/Crime/Crime.php FHUS|NonFiction/Arts/Arts.php FHUS|NonFiction/AutoBiographies/AutoBiographies.php FHUS|NonFiction/Cooking/Cooking.php FHUS|NonFiction/Crafts/Crafts.php FHUS|NonFiction/Education/Education.php FHUS|NonFiction/Gardening/Gardening.php FHUS|NonFiction/Health/Health.php FHUS|NonFiction/Hobbies/Hobbies.php FHUS|NonFiction/Humour/Humour.php FHUS|NonFiction/Outdoors/Outdoors.php FHUS|NonFiction/Reference/Reference.php FHUS|NonFiction/Religion/Religion.php FHUS|NonFiction/Sports/Sports.php FHUS|NonFiction/Technology/Technology.php FHUS|NonFiction/Travel/Travel.php FHUS|NonFiction/World/World.php FKUS|Fiction/Crime/Crime.php FHUS|Specialist/AntiquePre1950/AntiquePre1950.php FHUS|Specialist/Vintage1950To1975/Vintage1950To1975.php FHUS|Specialist/Retro1975To2000/Retro1975To2000.php FHUS|Specialist/FirstEditions/FirstEditions.php FHUS|Specialist/Classics/Classics.php FHUS|Specialist/Shakespeare/Shakespeare.php FHUS|Specialist/Penguin/Penguin.php FHUS|Specialist/BoxSets/BoxSets.php FHUS|Specialist/Series/Series.php FHUS|Specialist/ProlificAuthors/ProlificAuthors.php FHUS|Specialist/ReadersDigestCondensed/ReadersDigestCondensed.php FHUS|Specialist/MillsAndBoon/MillsAndBoon.php FHUS|Specialist/NationalGeographic/NationalGeographic.php FHUS|Specialist/Miscellaneous/Miscellaneous.php FHUS|Specialist/Penguin/Penguin.php FHUS|YoungAdults/YoungAdults.php FSUS|images/top.png FKUS|Fiction/Crime/Crime.php FSUS|images/home.png NHUS|index.htm FSUS|images/shopping_cart.png FHUS|ShoppingCart.php FSUS|images/shopping_cart.png
vti_cachedneedsrewrite:BR|false
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_metatags:VR|HTTP-EQUIV=Content-Type text/html;\\ charset=utf-8
vti_charset:SR|utf-8
