vti_encoding:SR|utf8-nl
vti_author:SR|DESKTOP-HJ9FAE6\\Cathy
vti_modifiedby:SR|LATITUDE-E5430\\gregaryb
vti_timelastmodified:TR|08 Mar 2024 09:50:08 -0000
vti_timecreated:TR|29 May 2023 07:26:58 -0000
vti_title:SR|Facebook
vti_extenderversion:SR|12.0.0.0
vti_nexttolasttimemodified:TR|08 Mar 2024 09:49:53 -0000
vti_backlinkinfo:VX|NonFiction/Construction/default.html NonFiction/Handyman/default.html NonFiction/Politics/default.html NonFiction/Culture/default.html NonFiction/Engineering/default.html NonFiction/Biographies/default.html NonFiction/Geography/default.html Fiction/Sci-Fi\\ Fanatasy/default.html Fiction/Political/default.html NonFiction/History/default.html NonFiction/Nature/default.html NonFiction/Science/default.html Facebook/Facebook.php NonFiction/Maths/default.html NonFiction/Food/default.html
vti_cacheddtm:TX|08 Mar 2024 09:50:08 -0000
vti_filesize:IR|14942
vti_cachedtitle:SR|Facebook
vti_cachedbodystyle:SR|<body>
vti_cachedlinkinfo:VX|G|../master.dwt Q|../styles/style2.css S|../global.js S|../images/Logo.png S|../images/Books.png H|../index.htm H|../FAQ/FAQ.php H|../LearnToCode/LearnToCode.html H|../Requests/Requests.html H|../Children/Children.php H|../Emporium/Emporium.php K|Facebook.php H|../Fiction/Action/Action.php H|../Fiction/Crime/Crime.php H|../Fiction/Fantasy.php H|../Fiction/General/General.php H|../Fiction/Horror/Horror.php H|../Fiction/Mystery/Mystery.php H|../Fiction/Romance/Romance.php H|../Fiction/Sagas/Sagas.php H|../Fiction/Science/science.php H|../Fiction/Thrillers/Thrillers.php H|../Fiction/Westerns/Westerners.html K|Facebook.php H|../NonFiction/Arts/Arts.php H|../NonFiction/AutoBiographies/AutoBiographies.php H|../NonFiction/Cooking/Cooking.php H|../NonFiction/Crafts/Crafts.php H|../NonFiction/Education/Education.php H|../NonFiction/Gardening/Gardening.php H|../NonFiction/Health/Health.php H|../NonFiction/Hobbies/Hobbies.php H|../NonFiction/Humour/Humour.php H|../NonFiction/Outdoors/Outdoors.php H|../NonFiction/Reference/Reference.php H|../NonFiction/Religion/Religion.php H|../NonFiction/Sports/Sports.php H|../NonFiction/Technology/Technology.php H|../NonFiction/Travel/Travel.php H|../NonFiction/World/World.php K|Facebook.php H|../Specialist/AntiquePre1950/AntiquePre1950.html H|../Specialist/Vintage1950To1975/Vintage1950To1975.html H|../Specialist/Retro1975To2000/Retro1975To2000.html H|../Specialist/FirstEditions/FirstEditions.html H|../Specialist/Classics/Classics.html H|../Specialist/Shakespeare/Shakespeare.html H|../Specialist/Penguin/Penguin.html H|../Specialist/BoxSets/BoxSets.html H|../Specialist/Series/Series.html H|../Specialist/ProlificAuthors/ProlificAuthors.html H|../Specialist/ReadersDigestCondensed/ReadersDigestCondensed.html H|../Specialist/MillsAndBoon/MillsAndBoon.html H|../Specialist/NationalGeographic/NationalGeographic.html H|../Specialist/Miscellaneous/Miscellaneous.html H|../Specialist/Penguin/Penguin.html S|../images/top.png K|Facebook.php S|../images/home.png H|../index.htm S|../images/shopping_cart.png H|../ShoppingCart.html S|../images/shopping_cart.png
vti_cachedsvcrellinks:VX|FGUS|master.dwt FQUS|styles/style2.css FSUS|global.js FSUS|images/Logo.png FSUS|images/Books.png NHUS|index.htm FHUS|FAQ/FAQ.php FHUS|LearnToCode/LearnToCode.html FHUS|Requests/Requests.html FHUS|Children/Children.php FHUS|Emporium/Emporium.php FKUS|Facebook/Facebook.php FHUS|Fiction/Action/Action.php FHUS|Fiction/Crime/Crime.php NHUS|Fiction/Fantasy.php FHUS|Fiction/General/General.php FHUS|Fiction/Horror/Horror.php FHUS|Fiction/Mystery/Mystery.php FHUS|Fiction/Romance/Romance.php FHUS|Fiction/Sagas/Sagas.php FHUS|Fiction/Science/science.php FHUS|Fiction/Thrillers/Thrillers.php NHUS|Fiction/Westerns/Westerners.html FKUS|Facebook/Facebook.php FHUS|NonFiction/Arts/Arts.php FHUS|NonFiction/AutoBiographies/AutoBiographies.php FHUS|NonFiction/Cooking/Cooking.php FHUS|NonFiction/Crafts/Crafts.php FHUS|NonFiction/Education/Education.php FHUS|NonFiction/Gardening/Gardening.php FHUS|NonFiction/Health/Health.php FHUS|NonFiction/Hobbies/Hobbies.php FHUS|NonFiction/Humour/Humour.php FHUS|NonFiction/Outdoors/Outdoors.php FHUS|NonFiction/Reference/Reference.php FHUS|NonFiction/Religion/Religion.php FHUS|NonFiction/Sports/Sports.php FHUS|NonFiction/Technology/Technology.php FHUS|NonFiction/Travel/Travel.php FHUS|NonFiction/World/World.php FKUS|Facebook/Facebook.php FHUS|Specialist/AntiquePre1950/AntiquePre1950.html FHUS|Specialist/Vintage1950To1975/Vintage1950To1975.html FHUS|Specialist/Retro1975To2000/Retro1975To2000.html FHUS|Specialist/FirstEditions/FirstEditions.html FHUS|Specialist/Classics/Classics.html FHUS|Specialist/Shakespeare/Shakespeare.html FHUS|Specialist/Penguin/Penguin.html FHUS|Specialist/BoxSets/BoxSets.html FHUS|Specialist/Series/Series.html FHUS|Specialist/ProlificAuthors/ProlificAuthors.html FHUS|Specialist/ReadersDigestCondensed/ReadersDigestCondensed.html FHUS|Specialist/MillsAndBoon/MillsAndBoon.html FHUS|Specialist/NationalGeographic/NationalGeographic.html FHUS|Specialist/Miscellaneous/Miscellaneous.html FHUS|Specialist/Penguin/Penguin.html FSUS|images/top.png FKUS|Facebook/Facebook.php FSUS|images/home.png NHUS|index.htm FSUS|images/shopping_cart.png FHUS|ShoppingCart.html FSUS|images/shopping_cart.png
vti_cachedneedsrewrite:BR|false
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_metatags:VR|HTTP-EQUIV=Content-Type text/html;\\ charset=utf-8
vti_charset:SR|utf-8
