vti_encoding:SR|utf8-nl
vti_author:SR|DESKTOP-KFJ8F7O\\boyle
vti_modifiedby:SR|LATITUDE-E5430\\gregaryb
vti_timelastmodified:TR|08 Mar 2024 03:51:53 -0000
vti_timecreated:TR|24 Jul 2023 05:03:10 -0000
vti_extenderversion:SR|12.0.0.0
vti_backlinkinfo:VX|NonFiction/Travel/Travel.php Children/Children.php Specialist/NationalGeographic/NationalGeographic.html LearnToCode/LearnToCode.html Specialist/AntiquePre1950/AntiquePre1950.html NonFiction/Crafts/Crafts.php NonFiction/Sports/Sports.php ShoppingCart.html Specialist/ReadersDigestCondensed/ReadersDigestCondensed.html Fiction/Action/Action.php Fiction/Westerns/Westerns.php Fiction/Mystery/Mystery.php Fiction/General/General.php NonFiction/Education/Education.php NonFiction/Gardening/Gardening.php NonFiction/Health/Health.php NonFiction/Reference/Reference.php Requests/Requests.html Specialist/BoxSets/BoxSets.html index.php NonFiction/Outdoors/Outdoors.php NonFiction/Hobbies/Hobbies.php NonFiction/Humour/Humour.php Specialist/Series/Series.html master.dwt Specialist/Vintage1950To1975/Vintage1950To1975.html NonFiction/AutoBiographies/AutoBiographies.php Specialist/FirstEditions/FirstEditions.html Specialist/Penguin/Penguin.html NonFiction/Cooking/Cooking.php NonFiction/Religion/Religion.php Specialist/Miscellaneous/Miscellaneous.html FAQ/FAQ.php Fiction/Sagas/Sagas.php Facebook/Facebook.php Emporium/Emporium.php YoungAdults/YoungAdults.html Fiction/Thrillers/Thrillers.php Fiction/Horror/Horror.php Fiction/Romance/Romance.php NonFiction/Technology/Technology.php NonFiction/World/World.php Specialist/Shakespeare/Shakespeare.html Fiction/Crime/Crime.php Specialist/Retro1975To2000/Retro1975To2000.html Specialist/MillsAndBoon/MillsAndBoon.html Specialist/ProlificAuthors/ProlificAuthors.html Fiction/Fantasy/Fantasy.php Specialist/Classics/Classics.html Fiction/Science/science.php NonFiction/Arts/Arts.php
vti_nexttolasttimemodified:TW|04 Aug 2023 12:56:03 -0000
vti_cacheddtm:TX|08 Mar 2024 03:51:53 -0000
vti_filesize:IR|34868
