vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|10 Mar 2024 08:04:15 -0000
vti_extenderversion:SR|12.0.0.0
vti_author:SR|LATITUDE-E5430\\gregaryb
vti_modifiedby:SR|LATITUDE-E5430\\gregaryb
vti_timecreated:TR|08 Mar 2024 03:51:53 -0000
vti_title:SR|Home
vti_backlinkinfo:VX|NonFiction/Travel/Travel.php Children/Children.php ShoppingCart.php Specialist/Shakespeare/shakespeare.php Specialist/vintage/vintage.php non_fiction/Hobbies/hobbies.php NonFiction/Crafts/Crafts.php Specialist/first_editions/first_editions.php Specialist/national_geographic/national_geographic.php Fiction/Action/action.php Fiction/General/general.php non_fiction/Cooking/cooking.php NonFiction/Gardening/Gardening.php NonFiction/Reference/Reference.php NonFiction/Sports/Sports.php index.php NonFiction/Humour/Humour.php Specialist/Classics/classics.php Specialist/Miscellaneous/miscellaneous.php Specialist/Series/series.php non_fiction/Health/health.php Emporium/Emporium.php Facebook/Facebook.php FAQ/FAQ.php Fiction/Horror/horror.php Fiction/Sagas/sagas.php Fiction/Thrillers/thrillers.php non_fiction/Gardening/gardening.php non_fiction/Humour/humour.php non_fiction/Reference/reference.php young_adults/young_adults.php YoungAdults/YoungAdults.php Fiction/Romance/romance.php non_fiction/AutoBiographies/autoBiographies.php non_fiction/Education/education.php NonFiction/Technology/Technology.php NonFiction/World/World.php Fiction/Crime/crime.php non_fiction/Outdoors/outdoors.php non_fiction/Religion/religion.php non_fiction/World/world.php Specialist/authors/authors.php Specialist/Penguin/penguin.php admin.php Fiction/Fantasy/fantasy.php Fiction/Science/science.php non_fiction/Travel/travel.php LearnToCode/LearnToCode.php non_fiction/Technology/technology.php NonFiction/Arts/Arts.php Specialist/mills_and_boon/mills_and_boon.php Specialist/readers_digest/readers_digest.php Fiction/Mystery/mystery.php Fiction/Westerns/westerns.php NonFiction/Education/Education.php NonFiction/Health/Health.php non_fiction/Crafts/crafts.php non_fiction/Sports/sports.php NonFiction/Hobbies/Hobbies.php NonFiction/Outdoors/Outdoors.php master.dwt NonFiction/AutoBiographies/AutoBiographies.php NonFiction/Cooking/Cooking.php NonFiction/Religion/Religion.php Requests/Requests.php Specialist/antiques/antique.php Specialist/box_sets/box_sets.php Specialist/retro/retro.php
vti_nexttolasttimemodified:TR|10 Mar 2024 07:55:26 -0000
vti_cacheddtm:TX|10 Mar 2024 08:04:15 -0000
vti_filesize:IR|17111
vti_cachedtitle:SR|Home
vti_cachedbodystyle:SR|<body>
vti_cachedlinkinfo:VX|G|master.dwt Q|styles/style.css S|images/Logo.png S|images/Books.png H|index.php H|FAQ/FAQ.php H|LearnToCode/LearnToCode.php H|Requests/Requests.php H|admin.php S|images/170\\ High\\ St.JPG S|images/170\\ High\\ St\\ Counter.JPG S|images/170\\ Front\\ of\\ shop.JPG S|images/170\\ Airplane\\ seats.JPG S|images/194\\ High\\ Piano.jpg S|images/194\\ High\\ Counter.jpg S|images/194\\ High\\ Airplane.jpg S|images/194\\ High\\ Childrens.jpg S|images/194\\ High\\ tables.jpg S|images/HomePageImage3.jpg S|images/HomePageImage1.jpg S|images/194\\ High\\ Cooking\\ Rack.jpg S|images/194\\ High\\ Front\\ Glass\\ Display.jpg S|images/194\\ High\\ Double\\ Glass\\ Display.jpg S|images/194\\ High\\ Shelves.jpg S|images/HomePageImage2.jpg S|images/top.png K|index.php S|images/home.png H|index.htm S|images/shopping_cart.png H|ShoppingCart.php S|images/shopping_cart.png
vti_cachedsvcrellinks:VX|FGUS|master.dwt FQUS|styles/style.css FSUS|images/Logo.png FSUS|images/Books.png FHUS|index.php FHUS|FAQ/FAQ.php FHUS|LearnToCode/LearnToCode.php FHUS|Requests/Requests.php FHUS|admin.php FSUS|images/170\\ High\\ St.JPG FSUS|images/170\\ High\\ St\\ Counter.JPG FSUS|images/170\\ Front\\ of\\ shop.JPG FSUS|images/170\\ Airplane\\ seats.JPG FSUS|images/194\\ High\\ Piano.jpg FSUS|images/194\\ High\\ Counter.jpg FSUS|images/194\\ High\\ Airplane.jpg FSUS|images/194\\ High\\ Childrens.jpg FSUS|images/194\\ High\\ tables.jpg FSUS|images/HomePageImage3.jpg FSUS|images/HomePageImage1.jpg FSUS|images/194\\ High\\ Cooking\\ Rack.jpg FSUS|images/194\\ High\\ Front\\ Glass\\ Display.jpg FSUS|images/194\\ High\\ Double\\ Glass\\ Display.jpg FSUS|images/194\\ High\\ Shelves.jpg FSUS|images/HomePageImage2.jpg FSUS|images/top.png FKUS|index.php FSUS|images/home.png NHUS|index.htm FSUS|images/shopping_cart.png FHUS|ShoppingCart.php FSUS|images/shopping_cart.png
vti_cachedneedsrewrite:BR|false
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_metatags:VR|HTTP-EQUIV=Content-Type text/html;\\ charset=utf-8
vti_charset:SR|utf-8
