vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|09 Mar 2024 12:56:03 -0000
vti_extenderversion:SR|12.0.0.0
vti_author:SR|LATITUDE-E5430\\gregaryb
vti_modifiedby:SR|LATITUDE-E5430\\gregaryb
vti_timecreated:TR|08 Mar 2024 03:51:53 -0000
vti_title:SR|Home
vti_backlinkinfo:VX|index.php
vti_nexttolasttimemodified:TR|09 Mar 2024 12:55:26 -0000
vti_cacheddtm:TX|09 Mar 2024 12:56:03 -0000
vti_filesize:IR|17062
vti_cachedtitle:SR|Home
vti_cachedbodystyle:SR|<body>
vti_cachedlinkinfo:VX|G|master.dwt Q|styles/style.css S|images/Logo.png S|images/Books.png H|index.htm H|FAQ/FAQ.php H|LearnToCode/LearnToCode.html H|Requests/Requests.php H|Children/Children.php H|Emporium/Emporium.php K|index.php H|Fiction/Action/Action.php H|Fiction/Crime/Crime.php H|Fiction/Fantasy/Fantasy.php H|Fiction/General/General.php H|Fiction/Horror/Horror.php H|Fiction/Mystery/Mystery.php H|Fiction/Romance/Romance.php H|Fiction/Sagas/Sagas.php H|Fiction/Science/science.php H|Fiction/Thrillers/Thrillers.php H|Fiction/Westerns/Westerns.php K|index.php H|NonFiction/Arts/Arts.php H|NonFiction/AutoBiographies/AutoBiographies.php H|NonFiction/Cooking/Cooking.php H|NonFiction/Crafts/Crafts.php H|NonFiction/Education/Education.php H|NonFiction/Gardening/Gardening.php H|NonFiction/Health/Health.php H|NonFiction/Hobbies/Hobbies.php H|NonFiction/Humour/Humour.php H|NonFiction/Outdoors/Outdoors.php H|NonFiction/Reference/Reference.php H|NonFiction/Religion/Religion.php H|NonFiction/Sports/Sports.php H|NonFiction/Technology/Technology.php H|NonFiction/Travel/Travel.php H|NonFiction/World/World.php K|index.php H|Specialist/AntiquePre1950/AntiquePre1950.php H|Specialist/Vintage1950To1975/Vintage1950To1975.php H|Specialist/Retro1975To2000/Retro1975To2000.php H|Specialist/FirstEditions/FirstEditions.php H|Specialist/Classics/Classics.php H|Specialist/Shakespeare/Shakespeare.php H|Specialist/Penguin/Penguin.php H|Specialist/BoxSets/BoxSets.php H|Specialist/Series/Series.php H|Specialist/ProlificAuthors/ProlificAuthors.php H|Specialist/ReadersDigestCondensed/ReadersDigestCondensed.php H|Specialist/MillsAndBoon/MillsAndBoon.php H|Specialist/NationalGeographic/NationalGeographic.php H|Specialist/Miscellaneous/Miscellaneous.php H|Specialist/Penguin/Penguin.php H|YoungAdults/YoungAdults.php S|images/170\\ High\\ St.JPG S|images/170\\ High\\ St\\ Counter.JPG S|images/170\\ Front\\ of\\ shop.JPG S|images/170\\ Airplane\\ seats.JPG S|images/194\\ High\\ Piano.jpg S|images/194\\ High\\ Counter.jpg S|images/194\\ High\\ Airplane.jpg S|images/194\\ High\\ Childrens.jpg S|images/194\\ High\\ tables.jpg S|images/HomePageImage3.jpg S|images/HomePageImage1.jpg S|images/194\\ High\\ Cooking\\ Rack.jpg S|images/194\\ High\\ Front\\ Glass\\ Display.jpg S|images/194\\ High\\ Double\\ Glass\\ Display.jpg S|images/194\\ High\\ Shelves.jpg S|images/HomePageImage2.jpg S|images/top.png K|index.php S|images/home.png H|index.htm S|images/shopping_cart.png H|ShoppingCart.php S|images/shopping_cart.png
vti_cachedsvcrellinks:VX|FGUS|master.dwt FQUS|styles/style.css FSUS|images/Logo.png FSUS|images/Books.png NHUS|index.htm FHUS|FAQ/FAQ.php FHUS|LearnToCode/LearnToCode.html FHUS|Requests/Requests.php FHUS|Children/Children.php FHUS|Emporium/Emporium.php FKUS|index.php FHUS|Fiction/Action/Action.php FHUS|Fiction/Crime/Crime.php FHUS|Fiction/Fantasy/Fantasy.php FHUS|Fiction/General/General.php FHUS|Fiction/Horror/Horror.php FHUS|Fiction/Mystery/Mystery.php FHUS|Fiction/Romance/Romance.php FHUS|Fiction/Sagas/Sagas.php FHUS|Fiction/Science/science.php FHUS|Fiction/Thrillers/Thrillers.php FHUS|Fiction/Westerns/Westerns.php FKUS|index.php FHUS|NonFiction/Arts/Arts.php FHUS|NonFiction/AutoBiographies/AutoBiographies.php FHUS|NonFiction/Cooking/Cooking.php FHUS|NonFiction/Crafts/Crafts.php FHUS|NonFiction/Education/Education.php FHUS|NonFiction/Gardening/Gardening.php FHUS|NonFiction/Health/Health.php FHUS|NonFiction/Hobbies/Hobbies.php FHUS|NonFiction/Humour/Humour.php FHUS|NonFiction/Outdoors/Outdoors.php FHUS|NonFiction/Reference/Reference.php FHUS|NonFiction/Religion/Religion.php FHUS|NonFiction/Sports/Sports.php FHUS|NonFiction/Technology/Technology.php FHUS|NonFiction/Travel/Travel.php FHUS|NonFiction/World/World.php FKUS|index.php FHUS|Specialist/AntiquePre1950/AntiquePre1950.php FHUS|Specialist/Vintage1950To1975/Vintage1950To1975.php FHUS|Specialist/Retro1975To2000/Retro1975To2000.php FHUS|Specialist/FirstEditions/FirstEditions.php FHUS|Specialist/Classics/Classics.php FHUS|Specialist/Shakespeare/Shakespeare.php FHUS|Specialist/Penguin/Penguin.php FHUS|Specialist/BoxSets/BoxSets.php FHUS|Specialist/Series/Series.php FHUS|Specialist/ProlificAuthors/ProlificAuthors.php FHUS|Specialist/ReadersDigestCondensed/ReadersDigestCondensed.php FHUS|Specialist/MillsAndBoon/MillsAndBoon.php FHUS|Specialist/NationalGeographic/NationalGeographic.php FHUS|Specialist/Miscellaneous/Miscellaneous.php FHUS|Specialist/Penguin/Penguin.php FHUS|YoungAdults/YoungAdults.php FSUS|images/170\\ High\\ St.JPG FSUS|images/170\\ High\\ St\\ Counter.JPG FSUS|images/170\\ Front\\ of\\ shop.JPG FSUS|images/170\\ Airplane\\ seats.JPG FSUS|images/194\\ High\\ Piano.jpg FSUS|images/194\\ High\\ Counter.jpg FSUS|images/194\\ High\\ Airplane.jpg FSUS|images/194\\ High\\ Childrens.jpg FSUS|images/194\\ High\\ tables.jpg FSUS|images/HomePageImage3.jpg FSUS|images/HomePageImage1.jpg FSUS|images/194\\ High\\ Cooking\\ Rack.jpg FSUS|images/194\\ High\\ Front\\ Glass\\ Display.jpg FSUS|images/194\\ High\\ Double\\ Glass\\ Display.jpg FSUS|images/194\\ High\\ Shelves.jpg FSUS|images/HomePageImage2.jpg FSUS|images/top.png FKUS|index.php FSUS|images/home.png NHUS|index.htm FSUS|images/shopping_cart.png FHUS|ShoppingCart.php FSUS|images/shopping_cart.png
vti_cachedneedsrewrite:BR|false
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_metatags:VR|HTTP-EQUIV=Content-Type text/html;\\ charset=utf-8
vti_charset:SR|utf-8
