vti_encoding:SR|utf8-nl
vti_author:SR|DESKTOP-HJ9FAE6\\Cathy
vti_modifiedby:SR|LATITUDE-E5430\\gregaryb
vti_timelastmodified:TR|26 Mar 2024 01:49:07 -0000
vti_timecreated:TR|29 May 2023 07:26:58 -0000
vti_title:SR|Shopping Cart
vti_extenderversion:SR|12.0.0.0
vti_nexttolasttimemodified:TW|25 Mar 2024 12:38:42 -0000
vti_backlinkinfo:VX|NonFiction/Travel/Travel.php Children/Children.php ShoppingCart.php Specialist/Shakespeare/shakespeare.php Specialist/vintage/vintage.php NonFiction/Crafts/Crafts.php Specialist/national_geographic/national_geographic.php non_fiction/Hobbies/hobbies.php Specialist/first_editions/first_editions.php NonFiction/Sports/Sports.php NonFiction/Reference/Reference.php Fiction/General/general.php Fiction/Action/action.php NonFiction/Gardening/Gardening.php non_fiction/Cooking/cooking.php Specialist/Classics/classics.php Specialist/Miscellaneous/miscellaneous.php index.php NonFiction/Humour/Humour.php Specialist/Series/series.php non_fiction/Health/health.php Emporium/Emporium.php non_fiction/Reference/reference.php FAQ/FAQ.php Fiction/Horror/horror.php Facebook/Facebook.php YoungAdults/YoungAdults.php Fiction/Sagas/sagas.php Fiction/Thrillers/thrillers.php non_fiction/Gardening/gardening.php non_fiction/Humour/humour.php young_adults/young_adults.php non_fiction/Education/education.php NonFiction/Technology/Technology.php NonFiction/World/World.php Fiction/Romance/romance.php non_fiction/AutoBiographies/autoBiographies.php Specialist/authors/authors.php Fiction/Crime/crime.php non_fiction/Outdoors/outdoors.php non_fiction/Religion/religion.php non_fiction/World/world.php Specialist/Penguin/penguin.php admin.php Fiction/Science/science.php Fiction/Fantasy/fantasy.php non_fiction/Travel/travel.php NonFiction/Arts/Arts.php non_fiction/Technology/technology.php Specialist/mills_and_boon/mills_and_boon.php Specialist/readers_digest/readers_digest.php LearnToCode/LearnToCode.php Fiction/Westerns/westerns.php Fiction/Mystery/mystery.php NonFiction/Education/Education.php NonFiction/Health/Health.php NonFiction/Outdoors/Outdoors.php NonFiction/Hobbies/Hobbies.php non_fiction/Crafts/crafts.php non_fiction/Sports/sports.php Requests/Requests.php master.dwt NonFiction/Cooking/Cooking.php NonFiction/AutoBiographies/AutoBiographies.php NonFiction/Religion/Religion.php Specialist/antiques/antique.php Specialist/box_sets/box_sets.php Specialist/retro/retro.php
vti_cacheddtm:TX|26 Mar 2024 01:49:07 -0000
vti_filesize:IR|25935
vti_cachedtitle:SR|Shopping Cart
vti_cachedbodystyle:SR|<body>
vti_cachedlinkinfo:VX|G|master.dwt Q|styles/style.css S|images/Logo.png S|images/Books.png S|images/CathysMobile.png S|images/CathysEmail.png H|< S|images/AdminEmail.png H|index.php H|FAQ/FAQ.php H|LearnToCode/LearnToCode.php H|Requests/Requests.php H|admin.php S|https://www.paypal.com/sdk/js H|https://www.anz.com.au/ways-to-bank/internet-banking/personal/ S|/images/ANZ.png H|https://ibanking.bankofmelbourne.com.au/ibank/loginPage.action S|/images/BOM.png H|https://www.bendigobank.com.au S|/images/BendigoBank.png H|https://www.my.commbank.com.au/netbank/Logon/Logon.aspx S|/images/Commonwealth.png H|https://www.macquarie.com.au S|/images/Macquarie.png H|https://www.nab.com.au/personal/online-banking S|/images/NAB.png H|https://ibanking.stgeorge.com.au/ibank/loginPage.action S|/images/StGeorge.png H|https://banking.westpac.com.au/wbc/banking/handler S|/images/Westpac.png S|images/top.png K|ShoppingCart.php S|images/home.png H|index.htm S|images/shopping_cart.png H|ShoppingCart.php S|images/shopping_cart.png
vti_cachedsvcrellinks:VX|FGUS|master.dwt FQUS|styles/style.css FSUS|images/Logo.png FSUS|images/Books.png FSUS|images/CathysMobile.png FSUS|images/CathysEmail.png DHUS|< FSUS|images/AdminEmail.png FHUS|index.php FHUS|FAQ/FAQ.php FHUS|LearnToCode/LearnToCode.php FHUS|Requests/Requests.php FHUS|admin.php NSSS|https://www.paypal.com/sdk/js NHSS|https://www.anz.com.au/ways-to-bank/internet-banking/personal/ NSUS|/images/ANZ.png NHSS|https://ibanking.bankofmelbourne.com.au/ibank/loginPage.action NSUS|/images/BOM.png NHSS|https://www.bendigobank.com.au NSUS|/images/BendigoBank.png NHSS|https://www.my.commbank.com.au/netbank/Logon/Logon.aspx NSUS|/images/Commonwealth.png NHSS|https://www.macquarie.com.au NSUS|/images/Macquarie.png NHSS|https://www.nab.com.au/personal/online-banking NSUS|/images/NAB.png NHSS|https://ibanking.stgeorge.com.au/ibank/loginPage.action NSUS|/images/StGeorge.png NHSS|https://banking.westpac.com.au/wbc/banking/handler NSUS|/images/Westpac.png FSUS|images/top.png FKUS|ShoppingCart.php FSUS|images/home.png NHUS|index.htm FSUS|images/shopping_cart.png FHUS|ShoppingCart.php FSUS|images/shopping_cart.png
vti_cachedneedsrewrite:BR|false
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_metatags:VR|HTTP-EQUIV=Content-Type text/html;\\ charset=utf-8
vti_charset:SR|utf-8
