vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|08 Mar 2024 14:08:36 -0000
vti_extenderversion:SR|12.0.0.0
vti_author:SR|DESKTOP-KFJ8F7O\\boyle
vti_modifiedby:SR|LATITUDE-E5430\\gregaryb
vti_timecreated:TR|18 Jul 2023 12:27:54 -0000
vti_title:SR|Westerns
vti_backlinkinfo:VX|Fiction/Westerns/Westerns.php
vti_nexttolasttimemodified:TR|08 Mar 2024 14:08:10 -0000
vti_cacheddtm:TX|08 Mar 2024 14:08:36 -0000
vti_filesize:IR|15000
vti_cachedtitle:SR|Westerns
vti_cachedbodystyle:SR|<body>
vti_cachedlinkinfo:VX|G|../../master.dwt Q|../../styles/style2.css S|../../global.js S|../../images/Logo.png S|../../images/Books.png H|../../index.htm H|../../FAQ/FAQ.php H|../../LearnToCode/LearnToCode.html H|../../Requests/Requests.php H|../../Children/Children.php H|../../Emporium/Emporium.php K|Westerns.php H|../Action/Action.php H|../Crime/Crime.php H|../Fantasy.php H|../General/General.php H|../Horror/Horror.php H|../Mystery/Mystery.php H|../Romance/Romance.php H|../Sagas/Sagas.php H|../Science/science.php H|../Thrillers/Thrillers.php H|Westerners.html K|Westerns.php H|../../NonFiction/Arts/Arts.php H|../../NonFiction/AutoBiographies/AutoBiographies.php H|../../NonFiction/Cooking/Cooking.php H|../../NonFiction/Crafts/Crafts.php H|../../NonFiction/Education/Education.php H|../../NonFiction/Gardening/Gardening.php H|../../NonFiction/Health/Health.php H|../../NonFiction/Hobbies/Hobbies.php H|../../NonFiction/Humour/Humour.php H|../../NonFiction/Outdoors/Outdoors.php H|../../NonFiction/Reference/Reference.php H|../../NonFiction/Religion/Religion.php H|../../NonFiction/Sports/Sports.php H|../../NonFiction/Technology/Technology.php H|../../NonFiction/Travel/Travel.php H|../../NonFiction/World/World.php K|Westerns.php H|../../Specialist/AntiquePre1950/AntiquePre1950.php H|../../Specialist/Vintage1950To1975/Vintage1950To1975.php H|../../Specialist/Retro1975To2000/Retro1975To2000.php H|../../Specialist/FirstEditions/FirstEditions.php H|../../Specialist/Classics/Classics.php H|../../Specialist/Shakespeare/Shakespeare.php H|../../Specialist/Penguin/Penguin.php H|../../Specialist/BoxSets/BoxSets.php H|../../Specialist/Series/Series.php H|../../Specialist/ProlificAuthors/ProlificAuthors.php H|../../Specialist/ReadersDigestCondensed/ReadersDigestCondensed.php H|../../Specialist/MillsAndBoon/MillsAndBoon.php H|../../Specialist/NationalGeographic/NationalGeographic.php H|../../Specialist/Miscellaneous/Miscellaneous.php H|../../Specialist/Penguin/Penguin.php S|../../images/top.png K|Westerns.php S|../../images/home.png H|../../index.htm S|../../images/shopping_cart.png H|../../ShoppingCart.php S|../../images/shopping_cart.png
vti_cachedsvcrellinks:VX|FGUS|master.dwt FQUS|styles/style2.css FSUS|global.js FSUS|images/Logo.png FSUS|images/Books.png NHUS|index.htm FHUS|FAQ/FAQ.php FHUS|LearnToCode/LearnToCode.html FHUS|Requests/Requests.php FHUS|Children/Children.php FHUS|Emporium/Emporium.php FKUS|Fiction/Westerns/Westerns.php FHUS|Fiction/Action/Action.php FHUS|Fiction/Crime/Crime.php NHUS|Fiction/Fantasy.php FHUS|Fiction/General/General.php FHUS|Fiction/Horror/Horror.php FHUS|Fiction/Mystery/Mystery.php FHUS|Fiction/Romance/Romance.php FHUS|Fiction/Sagas/Sagas.php FHUS|Fiction/Science/science.php FHUS|Fiction/Thrillers/Thrillers.php NHUS|Fiction/Westerns/Westerners.html FKUS|Fiction/Westerns/Westerns.php FHUS|NonFiction/Arts/Arts.php FHUS|NonFiction/AutoBiographies/AutoBiographies.php FHUS|NonFiction/Cooking/Cooking.php FHUS|NonFiction/Crafts/Crafts.php FHUS|NonFiction/Education/Education.php FHUS|NonFiction/Gardening/Gardening.php FHUS|NonFiction/Health/Health.php FHUS|NonFiction/Hobbies/Hobbies.php FHUS|NonFiction/Humour/Humour.php FHUS|NonFiction/Outdoors/Outdoors.php FHUS|NonFiction/Reference/Reference.php FHUS|NonFiction/Religion/Religion.php FHUS|NonFiction/Sports/Sports.php FHUS|NonFiction/Technology/Technology.php FHUS|NonFiction/Travel/Travel.php FHUS|NonFiction/World/World.php FKUS|Fiction/Westerns/Westerns.php FHUS|Specialist/AntiquePre1950/AntiquePre1950.php FHUS|Specialist/Vintage1950To1975/Vintage1950To1975.php FHUS|Specialist/Retro1975To2000/Retro1975To2000.php FHUS|Specialist/FirstEditions/FirstEditions.php FHUS|Specialist/Classics/Classics.php FHUS|Specialist/Shakespeare/Shakespeare.php FHUS|Specialist/Penguin/Penguin.php FHUS|Specialist/BoxSets/BoxSets.php FHUS|Specialist/Series/Series.php FHUS|Specialist/ProlificAuthors/ProlificAuthors.php FHUS|Specialist/ReadersDigestCondensed/ReadersDigestCondensed.php FHUS|Specialist/MillsAndBoon/MillsAndBoon.php FHUS|Specialist/NationalGeographic/NationalGeographic.php FHUS|Specialist/Miscellaneous/Miscellaneous.php FHUS|Specialist/Penguin/Penguin.php FSUS|images/top.png FKUS|Fiction/Westerns/Westerns.php FSUS|images/home.png NHUS|index.htm FSUS|images/shopping_cart.png FHUS|ShoppingCart.php FSUS|images/shopping_cart.png
vti_cachedneedsrewrite:BR|false
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_metatags:VR|HTTP-EQUIV=Content-Type text/html;\\ charset=utf-8
vti_charset:SR|utf-8
