vti_encoding:SR|utf8-nl
vti_author:SR|DESKTOP-HJ9FAE6\\Cathy
vti_modifiedby:SR|LATITUDE-E5430\\gregaryb
vti_timelastmodified:TR|09 Mar 2024 13:47:02 -0000
vti_timecreated:TR|29 May 2023 07:26:58 -0000
vti_title:SR|Young Adults
vti_extenderversion:SR|12.0.0.0
vti_nexttolasttimemodified:TR|09 Mar 2024 12:56:08 -0000
vti_backlinkinfo:VX|NonFiction/Sports/default.html NonFiction/Travel/Travel.php Specialist/FirstEditions/FirstEditions.php Fiction/Action/default.html ShoppingCart.php Specialist/Shakespeare/Shakespeare.php Children/Children.php LearnToCode/LearnToCode.html NonFiction/Crafts/Crafts.php Specialist/NationalGeographic/NationalGeographic.php Specialist/ReadersDigestCondensed/ReadersDigestCondensed.php Fiction/Crime/default.html NonFiction/Crafts/default.html Fiction/Action/Action.php Fiction/General/General.php NonFiction/Gardening/Gardening.php NonFiction/Reference/Reference.php NonFiction/Sports/Sports.php index.php NonFiction/Humour/Humour.php Specialist/AntiquePre1950/AntiquePre1950.php Specialist/Classics/Classics.php Specialist/Miscellaneous/Miscellaneous.php Specialist/Series/Series.php FAQ/default.html NonFiction/Cooking/default.html Specialist/MillsAndBoon/MillsAndBoon.php Fiction/Sagas/default.html Fiction/Fantasy/default.html YoungAdults/YoungAdults.php Facebook/Facebook.php Fiction/Horror/Horror.php Fiction/Sagas/Sagas.php Fiction/Thrillers/Thrillers.php Specialist/BoxSets/BoxSets.php Fiction/Mystery/default.html Fiction/Romance/Romance.php NonFiction/Technology/Technology.php NonFiction/World/World.php Specialist/Vintage1950To1975/Vintage1950To1975.php Requests/default.html Fiction/Horror/default.html Fiction/Crime/Crime.php Specialist/Penguin/Penguin.php Fiction/Fantasy/Fantasy.php Fiction/Science/science.php admin.php Facebook/default.html Fiction/Westerns/default.html Fiction/General/default.html NonFiction/Arts/Arts.php Fiction/Mystery/Mystery.php Fiction/Westerns/Westerns.php NonFiction/Education/Education.php NonFiction/Health/Health.php Specialist/ProlificAuthors/ProlificAuthors.php NonFiction/Hobbies/Hobbies.php NonFiction/Outdoors/Outdoors.php NonFiction/Travel/default.html Fiction/Thrillers/default.html master.dwt NonFiction/AutoBiographies/AutoBiographies.php NonFiction/Cooking/Cooking.php NonFiction/Religion/Religion.php Requests/Requests.php Specialist/Retro1975To2000/Retro1975To2000.php Fiction/Romance/default.html NonFiction/Arts/default.html NonFiction/AutoBiographies/default.html FAQ/FAQ.php Emporium/Emporium.php
vti_cacheddtm:TX|09 Mar 2024 13:47:02 -0000
vti_filesize:IR|12936
vti_cachedtitle:SR|Young Adults
vti_cachedbodystyle:SR|<body>
vti_cachedlinkinfo:VX|G|../master.dwt Q|../styles/style.css S|../images/Logo.png S|../images/Books.png H|../index.htm H|../FAQ/FAQ.php H|../LearnToCode/LearnToCode.html H|../Requests/Requests.php H|../Children/Children.php H|../Emporium/Emporium.php K|YoungAdults.php H|../Fiction/Action/Action.php H|../Fiction/Crime/Crime.php H|../Fiction/Fantasy/Fantasy.php H|../Fiction/General/General.php H|../Fiction/Horror/Horror.php H|../Fiction/Mystery/Mystery.php H|../Fiction/Romance/Romance.php H|../Fiction/Sagas/Sagas.php H|../Fiction/Science/science.php H|../Fiction/Thrillers/Thrillers.php H|../Fiction/Westerns/Westerns.php K|YoungAdults.php H|../NonFiction/Arts/Arts.php H|../NonFiction/AutoBiographies/AutoBiographies.php H|../NonFiction/Cooking/Cooking.php H|../NonFiction/Crafts/Crafts.php H|../NonFiction/Education/Education.php H|../NonFiction/Gardening/Gardening.php H|../NonFiction/Health/Health.php H|../NonFiction/Hobbies/Hobbies.php H|../NonFiction/Humour/Humour.php H|../NonFiction/Outdoors/Outdoors.php H|../NonFiction/Reference/Reference.php H|../NonFiction/Religion/Religion.php H|../NonFiction/Sports/Sports.php H|../NonFiction/Technology/Technology.php H|../NonFiction/Travel/Travel.php H|../NonFiction/World/World.php K|YoungAdults.php H|../Specialist/AntiquePre1950/AntiquePre1950.php H|../Specialist/Vintage1950To1975/Vintage1950To1975.php H|../Specialist/Retro1975To2000/Retro1975To2000.php H|../Specialist/FirstEditions/FirstEditions.php H|../Specialist/Classics/Classics.php H|../Specialist/Shakespeare/Shakespeare.php H|../Specialist/Penguin/Penguin.php H|../Specialist/BoxSets/BoxSets.php H|../Specialist/Series/Series.php H|../Specialist/ProlificAuthors/ProlificAuthors.php H|../Specialist/ReadersDigestCondensed/ReadersDigestCondensed.php H|../Specialist/MillsAndBoon/MillsAndBoon.php H|../Specialist/NationalGeographic/NationalGeographic.php H|../Specialist/Miscellaneous/Miscellaneous.php H|../Specialist/Penguin/Penguin.php H|YoungAdults.php H|../admin.php S|../images/top.png K|YoungAdults.php S|../images/home.png H|../index.htm S|../images/shopping_cart.png H|../ShoppingCart.php S|../images/shopping_cart.png
vti_cachedsvcrellinks:VX|FGUS|master.dwt FQUS|styles/style.css FSUS|images/Logo.png FSUS|images/Books.png NHUS|index.htm FHUS|FAQ/FAQ.php FHUS|LearnToCode/LearnToCode.html FHUS|Requests/Requests.php FHUS|Children/Children.php FHUS|Emporium/Emporium.php FKUS|YoungAdults/YoungAdults.php FHUS|Fiction/Action/Action.php FHUS|Fiction/Crime/Crime.php FHUS|Fiction/Fantasy/Fantasy.php FHUS|Fiction/General/General.php FHUS|Fiction/Horror/Horror.php FHUS|Fiction/Mystery/Mystery.php FHUS|Fiction/Romance/Romance.php FHUS|Fiction/Sagas/Sagas.php FHUS|Fiction/Science/science.php FHUS|Fiction/Thrillers/Thrillers.php FHUS|Fiction/Westerns/Westerns.php FKUS|YoungAdults/YoungAdults.php FHUS|NonFiction/Arts/Arts.php FHUS|NonFiction/AutoBiographies/AutoBiographies.php FHUS|NonFiction/Cooking/Cooking.php FHUS|NonFiction/Crafts/Crafts.php FHUS|NonFiction/Education/Education.php FHUS|NonFiction/Gardening/Gardening.php FHUS|NonFiction/Health/Health.php FHUS|NonFiction/Hobbies/Hobbies.php FHUS|NonFiction/Humour/Humour.php FHUS|NonFiction/Outdoors/Outdoors.php FHUS|NonFiction/Reference/Reference.php FHUS|NonFiction/Religion/Religion.php FHUS|NonFiction/Sports/Sports.php FHUS|NonFiction/Technology/Technology.php FHUS|NonFiction/Travel/Travel.php FHUS|NonFiction/World/World.php FKUS|YoungAdults/YoungAdults.php FHUS|Specialist/AntiquePre1950/AntiquePre1950.php FHUS|Specialist/Vintage1950To1975/Vintage1950To1975.php FHUS|Specialist/Retro1975To2000/Retro1975To2000.php FHUS|Specialist/FirstEditions/FirstEditions.php FHUS|Specialist/Classics/Classics.php FHUS|Specialist/Shakespeare/Shakespeare.php FHUS|Specialist/Penguin/Penguin.php FHUS|Specialist/BoxSets/BoxSets.php FHUS|Specialist/Series/Series.php FHUS|Specialist/ProlificAuthors/ProlificAuthors.php FHUS|Specialist/ReadersDigestCondensed/ReadersDigestCondensed.php FHUS|Specialist/MillsAndBoon/MillsAndBoon.php FHUS|Specialist/NationalGeographic/NationalGeographic.php FHUS|Specialist/Miscellaneous/Miscellaneous.php FHUS|Specialist/Penguin/Penguin.php FHUS|YoungAdults/YoungAdults.php FHUS|admin.php FSUS|images/top.png FKUS|YoungAdults/YoungAdults.php FSUS|images/home.png NHUS|index.htm FSUS|images/shopping_cart.png FHUS|ShoppingCart.php FSUS|images/shopping_cart.png
vti_cachedneedsrewrite:BR|false
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_metatags:VR|HTTP-EQUIV=Content-Type text/html;\\ charset=utf-8
vti_charset:SR|utf-8
